### ISSUE TITLE
Adding support for float and it's variant

### ISSUE THREAD

**Issue by bignyap** [hexon/mysqltsv#1]
Adding the following line at (https://github.com/hexon/mysqltsv/blob/2b86f827d04d8756e4837073ecf512595e49bc90/mysqltsv.go#L213C2-L213C9)](https://github.com/hexon/mysqltsv/blob/2b86f827d04d8756e4837073ecf512595e49bc90/mysqltsv.go#L213C2-L213C9) fixes the issue for float64. We have to handle all the other variants of float.

This is causing issue in https://github.com/sqlc-dev/sqlc/issues/3677

```
case float64:
    return []byte(strconv.FormatFloat(v, 'f', -1, 64)), nil
```

**Comment by Jille** [comment]
Would you mind testing this with `go get github.com/hexon/mysqltsv@01b8881b2730ac29e76ef072d53691acb8e59908`? If it works I'll tag it.

**Comment by bignyap** [comment]
Yes, it worked.

**Comment by Jille** [comment]
Tagged v0.2.2. Thanks!
